version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: booklibrarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - book-net

  backend:
    image: arkhanpstucse/library-backend:latest
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/booklibrarydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - book-net

  frontend:
    image: arkhanpstucse/library_frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - book-net

networks:
  book-net:
    driver: bridge